### ISSUE TITLE
Error on trying to install

### ISSUE THREAD

**Issue by fgodoy** [bahmutov/cypress-failed-log#282]
Hi. It's anyone know whats happening? 

In the past works, now cannot install.

Thanks.

# npm install --save-dev cypress cypress-failed-log
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> cypress@9.1.0 postinstall /app/node_modules/cypress
> node index.js --exec install

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'har-validator'
Require stack:
- /app/node_modules/@cypress/request/lib/har.js
- /app/node_modules/@cypress/request/request.js
- /app/node_modules/@cypress/request/index.js
- /app/node_modules/cypress/lib/tasks/download.js
- /app/node_modules/cypress/lib/tasks/install.js
- /app/node_modules/cypress/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/@cypress/request/lib/har.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/@cypress/request/request.js:23:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@cypress/request/lib/har.js',
    '/app/node_modules/@cypress/request/request.js',
    '/app/node_modules/@cypress/request/index.js',
    '/app/node_modules/cypress/lib/tasks/download.js',
    '/app/node_modules/cypress/lib/tasks/install.js',
    '/app/node_modules/cypress/index.js'
  ]
}
npm WARN enoent ENOENT: no such file or directory, open '/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@9.1.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@9.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-25T12_37_35_241Z-debug.log

I flow this to install:

apt-get update -yq 
apt-get install curl gnupg -yq 
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs
apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
npm install --save-dev cypress cypress-failed-log
npm install cypress-mochawesome-reporter
npx @bahmutov/cly init

**Comment by fgodoy** [comment]
I install manually and works:

npm install --save-dev cypress cypress-failed-log

I don't now what was change to be needed install, previously it was already installed.

Thanks.
